module.exports.init = async () => {
  const nm = api.nexomaker;
  
  api.console.log('🇩🇪 German language pack loading...');

  nm.postLanguage({
    local: 'de',
    label: 'Deutsch',

    // ===== SIDEBAR =====
    sidebar: {
      create_item: 'Neues Item erstellen',
      create_item_desc: 'Erstelle benutzerdefinierte Items mit einzigartigen Texturen und Eigenschaften',
      create_weapon: 'Neue Waffe erstellen',
      create_weapon_desc: 'Schmiede mächtige Waffen mit individuellem Schaden und Effekten',
      create_block: 'Neuen Block erstellen',
      create_block_desc: 'Gestalte benutzerdefinierte Blöcke mit Texturen und Verhalten',
      create_furniture: 'Neue Möbel erstellen',
      create_furniture_desc: 'Baue dekorative Möbel und interaktive Objekte',
      create_entity: 'Neue Kreatur erstellen',
      create_entity_desc: 'Erstelle benutzerdefinierte Mobs und Kreaturen mit Animationen',
      create_event: 'Neues Event erstellen',
      create_event_desc: 'Richte benutzerdefinierte Events und Auslöser für deinen Inhalt ein',
      create_food: 'Neues Essen erstellen',
      create_food_desc: 'Kreiere benutzerdefinierte Nahrungsmittel mit Ernährungseffekten',
      create_tool: 'Neues Werkzeug erstellen',
      create_tool_desc: 'Stelle benutzerdefinierte Werkzeuge mit einzigartigen Fähigkeiten her',
      create_glyph: 'Neue Glyphe erstellen',
      create_glyph_desc: 'Gestalte benutzerdefinierte Unicode-Glyphen und Emojis',
      create_armor: 'Neue Rüstung erstellen',
      create_armor_desc: 'Gestalte benutzerdefinierte Rüstungssets mit einzigartigen Texturen',
      create_gui: 'Neues GUI erstellen',
      create_gui_desc: 'Gestalte benutzerdefinierte Inventarbildschirme und Menüs',
      create_crop: 'Neue Pflanze erstellen',
      create_crop_desc: 'Baue benutzerdefinierte Pflanzen mit mehrstufigen Texturen',
      add_content: 'Inhalt hinzufügen',
      add_content_tooltip: 'Füge Inhalt zu deinem Projekt hinzu',
      projects: 'Projekte',
      projects_tooltip: 'Verwalte den Inhalt deines Projekts',
      environment: 'Umgebung',
      environment_tooltip: 'Teste deine Änderungen auf einem lokalen Server',
      expansions: 'Erweiterungen',
      expansions_tooltip: 'Erweiterungen und NMCrate',
      settings: 'Einstellungen',
      settings_tooltip: 'Projekt-Einstellungen',
      leave_project: 'Projekt verlassen',
      leave_project_tooltip: 'Aktuelles Projekt verlassen',
      add_module: 'Modul hinzufügen',
      no_creators_available: 'Keine Ersteller für dieses Plugin verfügbar',
      no_creators_subtitle: 'Wenn du der Entwickler bist, stelle sicher, dass die Kompatibilität deines Plugins eingerichtet ist'
    },

    // ===== PROJECT WINDOW =====
    project_window: {
      new_project: 'Neues Projekt',
      import_project: 'Projekt importieren',
      user_profile: 'Benutzerprofil',
      logout: 'Abmelden',
      upgrade: 'Upgraden',
      update_available: 'Update auf Version {version} ist jetzt verfügbar',
      update: 'Aktualisieren',
      loading_projects: 'Projekte werden geladen...',
      matching_projects: 'Passende Projekte',
      projects: 'Projekte',
      search_placeholder: 'Suchen...',
      project_format: 'Projekt-Format',
      project_name: 'Projektname',
      last_modification: 'Letzte Änderung',
      version: 'Version',
      no_projects_loaded: 'Keine Projekte geladen',
      author: 'Autor',
      plugins: 'Plugins',
      label_empty: 'Leer',
      drop_plugins: 'Lege deine Plugins hier ab',
      plugins_list: 'Plugins-Liste',
      project_file: 'Projekt-Datei',
      drop_project_file: 'Lege deine Projekt-Datei hier ab',
      details: 'Details',
      plugins_optional: 'Plugins (optional)',
      review: 'Überprüfen',
      eula_accept: 'Ich habe die',
      none: 'Keine',
      language: 'Sprache',
      cloud_sync: 'Cloud-Synchronisierung',
      coming_soon: 'Demnächst verfügbar',
      edited: 'Bearbeitet',
      no_matching_projects: 'Keine passenden Projekte',
      no_projects_found: 'Keine Projekte gefunden',
      try_adjusting_search: 'Passe deine Suchbegriffe an',
      get_started_first_project: 'Beginne mit der Erstellung deines ersten Projekts',
      sign_in: 'Anmelden',
      premium_plan: 'Premium-Plan',
      premium_features_unlocked: 'Alle Premium-Funktionen sind freigeschaltet.',
      no_notifications: 'Du hast keine Benachrichtigungen',
      news: 'Neuigkeiten',
      nothing_to_show: 'Hier gibt es nichts anzuzeigen',
      delete_project: 'Projekt löschen',
      delete_projects: '{count} Projekte löschen',
      whats_new_in: 'Was gibt es Neues in {version}',
      new: 'Neu',
      swipe_to_dismiss: 'Zum Schließen streichen',
      dismiss: 'Schließen',
      changelog_subtitle: 'Hier ist alles, woran wir gearbeitet haben'
    },

    // ===== APP SETTINGS =====
    app_settings: {
      display: 'Anzeige',
      system: 'System',
      updates: 'Updates',
      advanced: 'Erweitert',
      three_d_view: '3D-Ansicht',
      extras: 'Extras',
      language: 'Sprache',
      language_desc: 'Ändere die Sprache der gesamten Anwendung.',
      zoom: 'Zoom',
      zoom_desc: 'Ändert die GUI-Skalierung. Wähle eine Zoomstufe aus oder klicke auf Zurücksetzen, um zu 100 % zurückzukehren.',
      session_saving: 'Sitzung speichern',
      session_saving_desc: 'Stelle dein letztes Projekt und die geöffneten Tabs beim App-Start wieder her.',
      enable_sounds: 'Sounds aktivieren',
      enable_sounds_desc: 'Spiele Soundeffekte und Benachrichtigungen ab',
      enable_notifications: 'Benachrichtigungen aktivieren',
      enable_notifications_desc: 'Zeige Desktop-Benachrichtigungen für wichtige Ereignisse an',
      debug_mode: 'Debug-Modus',
      debug_mode_desc: 'Aktiviere detaillierte Konsolenprotokollierung zum Debuggen',
      blockbench_path: 'Blockbench-Pfad',
      blockbench_path_desc: 'Benutzerdefinierter Pfad zur Blockbench-ausführbaren Datei. Leer lassen für automatische Erkennung.',
      blockbench_path_placeholder: 'Automatische Erkennung (leer lassen)',
      blockbench_download_text: 'Blockbench nicht installiert?',
      blockbench_download_link: 'Hier herunterladen',
      enable_auto_updates: 'Automatische Updates aktivieren',
      enable_auto_updates_desc: 'Erlaube der App, sich selbst zu aktualisieren und nach Updates automatisch neu zu starten.',
      beta_updates: 'Beta-Updates',
      beta_updates_desc: 'Alle Versionen sind derzeit Beta-Versionen, daher ist dies immer aktiviert. Es wird optional, sobald stabile Versionen existieren.',
      check_for_updates: 'Nach Updates suchen',
      check_for_updates_desc: 'Manuell nach einer neueren Version der App suchen.',
      clear_cache: 'Cache leeren',
      clear_cache_desc: 'Entferne zwischengespeicherte Daten, um Speicherplatz freizugeben und Probleme zu beheben.',
      reset_settings: 'Einstellungen zurücksetzen',
      reset_settings_desc: 'Alle Einstellungen auf ihre Standardwerte zurücksetzen.',
      beta_features: 'Beta-Funktionen',
      beta_features_desc: 'Aktiviere experimentelle Funktionen, die sich noch in der Entwicklung befinden.',
      blueprint_pinned_camera: 'Blueprint-Ansicht Kamera fixieren',
      blueprint_pinned_camera_desc: 'Wenn aktiviert, kehrt die Kamera in der Blueprint-Ansicht in die Mittelposition zurück.',
      item_preview_animation: 'Item-Editor Vorschau-Animation',
      item_preview_animation_desc: 'Wenn aktiviert, dreht sich das 3D-Modell automatisch bei der Darstellung im Item-Editor.'
    },

    // ===== PROJECT SETTINGS (WICHTIG!) =====
    project_settings: {
      unsaved_changes: 'Ungespeicherte Änderungen',
      saving_changes: 'Änderungen werden gespeichert...',
      save: 'Speichern',
      saving: 'Speichern...',
      discard: 'Verwerfen',
      
      // Categories
      category_project: 'PROJEKT-EINSTELLUNGEN',
      category_environment: 'UMGEBUNG',
      category_expansions: 'ERWEITERUNGEN',
      category_actions: 'AKTIONEN',
      
      // General section
      general: 'Allgemein',
      general_desc: 'Konfiguriere grundlegende Projektinformationen und -einstellungen. Diese Einstellungen definieren die Identität deines Projekts und die Ziel-Minecraft-Version.',
      project_id: 'Projekt-ID',
      project_id_desc: 'Eindeutige Kennung für dein Projekt. Darf keine Leerzeichen oder Sonderzeichen enthalten.',
      project_id_hint: 'Die Projekt-ID darf nur Kleinbuchstaben, Zahlen und Bindestriche enthalten',
      project_format: 'Projekt-Format',
      project_format_desc: 'Das primäre Format des Projekts (z.B. nexo, itemsadder).',
      project_name: 'Projektname',
      project_name_desc: 'Anzeigename für dein Projekt.',
      project_name_placeholder: 'Mein großartiges Projekt',
      author: 'Autor',
      author_desc: 'Der Ersteller oder Betreuer dieses Projekts.',
      author_placeholder: 'Dein Name',
      
      // Export Settings
      export_settings: 'Export-Einstellungen',
      entity_model_exporter: 'Entity-Modell-Exporter',
      entity_model_exporter_desc: 'Plugin zum Exportieren von 3D-Entity-Modellen (BBModels). Wähle zwischen ModelEngine oder BetterModel.',
      entity_behavior_exporter: 'Entity-Verhalten-Exporter',
      entity_behavior_exporter_desc: 'Plugin zum Exportieren von Entity-KI- und Verhaltenskonfiguration.',
      scripting_exporter: 'Skript-Exporter',
      scripting_exporter_desc: 'Plugin zum Exportieren von NMScript zu Serverskripten.',
      select_exporter: 'Exporter auswählen...',
      no_content_for_category: 'Für diese Kategorie wird kein Exporter benötigt',
      no_exporters_available: 'Keine Exporter verfügbar',
      
      // About section
      about: 'Info',
      about_desc: 'Zeige schreibgeschützte Informationen über dein Projekt an, einschließlich Erstellungsdatum, Dateispeicherort und aktuelle Konfiguration.',
      project_path: 'Projekt-Pfad',
      project_path_desc: 'Dateisystem-Speicherort des Projekts.',
      date_created: 'Erstellungsdatum',
      date_created_desc: 'Wann dieses Projekt erstellt wurde.',
      minecraft_version: 'Minecraft-Version',
      minecraft_version_desc: 'Die Minecraft-Version, die dieses Projekt anvisiert.',
      
      // Plugins section
      plugins: 'Plugins',
      plugins_desc: 'Verwalte Server-Plugins durch Hochladen von .jar-Dateien. Diese Plugins erweitern die Funktionalität deines Servers mit neuen Funktionen und Befehlen.',
      plugin_manager: 'Plugin-Manager',
      plugin_manager_desc: 'Lade .jar-Plugin-Dateien für deinen Server hoch und verwalte sie.',
      
      // Advanced section
      advanced: 'Erweitert',
      advanced_desc: 'Konfiguriere erweiterte Servereinstellungen für erfahrene Benutzer. Diese Einstellungen beeinflussen die Serverleistung und Debugging-Funktionen.',
      memory_allocation: 'Speicherzuweisung',
      memory_allocation_desc: 'Java-Speicherlimit in Megabyte (MB). Höhere Werte ermöglichen mehr Plugins und Spieler.',
      memory_allocation_hint: 'Empfohlen: 2048 MB für 1-4 Plugins, 4096+ MB für größere Setups',
      jvm_header: 'JAVA VIRTUAL MACHINE',
      custom_jvm_args: 'Benutzerdefinierte JVM-Argumente',
      custom_jvm_args_desc: 'Zusätzliche JVM-Argumente für fortgeschrittene Benutzer. Leer lassen für Standardeinstellungen.',
      custom_jvm_args_placeholder: '-XX:+UseG1GC -XX:MaxGCPauseMillis=50',
      custom_jvm_args_hint: 'Beispiel: -XX:+UseG1GC -XX:MaxGCPauseMillis=50 für optimierte Garbage Collection',
      
      // Server Properties
      server_properties: 'Server-Eigenschaften',
      server_properties_desc: 'Konfiguriere das Verhalten und die Einstellungen deines Minecraft-Servers. Nutze die Suchfunktion, um schnell bestimmte Eigenschaften zu finden.',
      search_server_properties: 'Server-Eigenschaften durchsuchen...',
      
      // Instances
      instances: 'Instanzen',
      instances_title: 'Server-Instanzen',
      instances_desc: 'Zeige alle Server-Instanzen für dieses Projekt an und verwalte sie. Jede Instanz repräsentiert eine andere Minecraft-Version.',
      server_instances: 'Server-Instanzen',
      server_instances_desc: 'Wechsle zwischen Server-Instanzen oder entferne ungenutzte, um Speicherplatz freizugeben.',
      
      // Expansions
      expansions: 'Erweiterungen',
      expansions_title: 'Installierte Erweiterungen',
      expansions_desc: 'Zeige alle installierten Erweiterungen für dieses Projekt an und verwalte sie. Erweiterungen fügen neue Inhaltstypen, Funktionen und Funktionalitäten zu Nexo Maker hinzu.',
      installed_expansions: 'Installierte Erweiterungen',
      installed_expansions_desc: 'Durchsuche deine installierten Erweiterungen, prüfe auf Updates oder deinstalliere nicht mehr benötigte Erweiterungen.',
      search_installed_expansions: 'Installierte Erweiterungen durchsuchen...',
      loading_expansions: 'Erweiterungen werden geladen...',
      all: 'Alle',
      store: 'Store',
      local: 'Lokal',
      errors: 'Fehler',
      expansion_singular: 'Erweiterung',
      expansions_plural: 'Erweiterungen',
      grid_view: 'Rasteransicht',
      list_view: 'Listenansicht',
      no_expansions_found: 'Keine Erweiterungen gefunden',
      try_adjusting_filters: 'Passe deine Suche oder Filter an',
      clear_search: 'Suche löschen',
      no_expansions_installed: 'Noch keine Erweiterungen installiert',
      browse_store: 'Durchsuche den Erweiterungs-Store, um Erweiterungen zu finden und zu installieren',
      explore_expansions: 'Erweiterungen erkunden',
      uninstall_expansion: 'Erweiterung deinstallieren',
      uninstall_expansion_confirm: 'Möchtest du diese Erweiterung wirklich deinstallieren? Diese Aktion kann nicht rückgängig gemacht werden.',
      uninstall: 'Deinstallieren',
      failed_uninstall_expansion: 'Deinstallation der Erweiterung fehlgeschlagen',
      unknown_source: 'Unbekannte Quelle',
      unknown_version: 'Unbekannt',
      unknown_error: 'Unbekannter Fehler',
      local_developer: 'Lokaler Entwickler',
      expansion_error: 'Fehler',
      local_development: 'Lokale Entwicklung',
      by: 'von',
      update: 'Aktualisieren',
      remove: 'Entfernen',
      source_error: 'Quelle (Fehler)',
      source_code: 'Quellcode',
      
      // Export section
      export: 'Export',
      export_desc: 'Exportiere dein Projekt in verschiedenen Formaten, die mit anderen geteilt oder auf verschiedenen Plattformen verwendet werden können.',
      project_package: 'NMPackage-Projekt',
      project_package_desc: 'Exportiere dein Projekt als portable .nxp-Datei, die mit anderen geteilt oder in eine andere Nexo Maker-Installation importiert werden kann.',
      production_pack: 'Produktions-Pack',
      production_pack_desc: 'Exportiere ein komplettes serverfertiges Pack mit anpassbaren Exporteuren für jeden Inhaltstyp.',
      nexo_format_desc: 'Exportiere dein Projekt im Nexo-Plugin-Format für die Verwendung mit Paper/Spigot-Servern.',
      itemsadder_format_desc: 'Exportiere dein Projekt im ItemsAdder-Plugin-Format für die Verwendung mit Paper/Spigot-Servern.',
      export_format_generic: 'Exportiere dein Projekt im {format}-Format.',
      generating_package: 'Erstelle {format}-Paket...',
      please_wait_export: 'Bitte warte, während wir deinen Export vorbereiten.',
      built_in: 'Integriert',
      source: 'Quelle',
      generating: 'Erstelle...',
      export_format: 'Exportiere {format}',
      install_expansions_export: 'Installiere Erweiterungen mit exportierbaren Formaten, um weitere Exportoptionen zu sehen.',
      note: 'Hinweis',
      only_can_export_shown: 'Nur Formate mit',
      are_shown_here: 'werden hier angezeigt',
      
      // Backup section
      backup: 'Backup',
      backup_desc: 'Erstelle zeitgestempelte Backups deines Projekts, die später wiederhergestellt werden können. Regelmäßige Backups schützen deine Arbeit vor versehentlichen Änderungen oder Beschädigungen.',
      create_backup: 'Backup erstellen',
      create_backup_desc: 'Erstelle ein zeitgestempeltes Backup deines Projekts, das später wiederhergestellt werden kann.',
      
      // Delete Project
      delete_project: 'Projekt löschen',
      delete_project_desc: 'Entferne dieses Projekt dauerhaft von deinem System. Diese Aktion kann nicht rückgängig gemacht werden. Stelle sicher, dass du bei Bedarf vorher ein Backup erstellst.',
      delete_project_action: 'Projekt löschen',
      delete_project_action_desc: 'Lösche dieses Projekt dauerhaft. Diese Aktion kann nicht rückgängig gemacht werden.',
      delete_project_title: 'Projekt löschen',
      
      // Plugin Manager
      add_plugin: 'Plugin hinzufügen',
      remove_plugin: 'Plugin entfernen',
      remove_plugin_title: 'Plugin entfernen',
      drag_drop_jar: '.jar-Dateien hier ablegen',
      click_browse: 'oder zum Durchsuchen klicken',
      no_plugins: 'Keine Plugins installiert',
      upload_jar_extend: 'Lade .jar-Dateien hoch, um die Server-Funktionalität zu erweitern',
      plugin_name: 'Plugin-Name',
      file_name: 'Dateiname',
      file_size: 'Dateigröße',
      search_plugins: 'Plugins durchsuchen...',
      
      // Instances Manager
      create_instance: 'Instanz erstellen',
      delete_instance: 'Löschen',
      rename_instance: 'Umbenennen',
      switch_version: 'Wechseln',
      cancel: 'Abbrechen',
      save: 'Speichern',
      ok: 'OK',
      confirm: 'Bestätigen',
      switch_instance_title: 'Server-Version wechseln',
      switch_instance_message: 'Der Wechsel der Server-Version wird den Testserver neu starten. Fortfahren?',
      cannot_delete: 'Kann nicht gelöscht werden',
      cannot_delete_active: 'Die aktuell aktive Instanz kann nicht gelöscht werden. Wechsle zuerst zu einer anderen Version.',
      delete_server_instance: 'Server-Instanz löschen',
      delete_instance_confirm: 'Möchtest du "{name}" wirklich löschen? Dies wird alle Serverdaten, Plugins und Welten dauerhaft entfernen.',
      instance_deleted: 'Instanz gelöscht',
      deleted_instance: 'Instanz "{name}" wurde gelöscht',
      error: 'Fehler',
      failed_delete_instance: 'Löschen der Instanz fehlgeschlagen',
      failed_rename_instance: 'Umbenennen der Instanz fehlgeschlagen'
    },

    // ===== ITEM EDITOR =====
    item_editor: {
      format_bold: 'Fett',
      format_italic: 'Kursiv',
      format_underline: 'Unterstrichen',
      format_strikethrough: 'Durchgestrichen',
      format_color: 'Textfarbe',
      format_gradient: 'Farbverlauf',
      format_clear: 'Formatierung löschen',
      gradient_start: 'Farbverlauf Start',
      gradient_end: 'Farbverlauf Ende',
      add_line: 'Zeile hinzufügen',
      remove_line: 'Zeile entfernen',
      loading_item_data: 'Item-Daten werden geladen...',
      item_not_found: 'Item nicht gefunden.',
      item_not_found_desc: 'Es wurde möglicherweise gelöscht oder noch nicht geladen.',
      search_modules: 'Module durchsuchen...',
      no_modules_added: 'Keine Module hinzugefügt',
      click_drag_to_add: 'Klicke oder ziehe hier, um Item-Module hinzuzufügen',
      add_module: 'Modul hinzufügen',
      delete_module: 'Modul löschen',
      view_module_info: 'Modul-Informationen anzeigen',
      select: 'Auswählen',
      deselect: 'Abwählen',
      create_group: 'Gruppe erstellen ({count} Module)',
      delete: 'Löschen',
      no_model: 'Kein Modell',
      beta_feature: 'Beta-Funktion',
      three_d_view: '3D-Ansicht',
      refresh: 'Aktualisieren',
      assets: 'Assets',
      open_assets_folder: 'Assets-Ordner öffnen',
      click_to_preview: 'Klicke, um {filename} vorzusehen',
      lore: 'Lore',
      enter_lore: 'Gib Lore ein, jede Zeile wird ein neues Element',
      loading_items: 'Items werden geladen...',
      effects: 'Effekte',
      search_effects: 'Effekte durchsuchen...',
      add_effect: 'Effekt hinzufügen',
      level: 'Stufe',
      duration: 'Dauer',
      duration_seconds: 'Dauer (Sekunden)',
      is_ambient: 'Ist Ambient',
      show_particles: 'Partikel anzeigen',
      show_icon: 'Symbol anzeigen',
      no_effects: 'Keine Effekte hinzugefügt',
      crafting: 'Herstellung',
      crafting_recipe: 'Handwerksrezept',
      module_info_name: 'Name',
      module_info_display_name: 'Anzeigename',
      module_info_type: 'Typ',
      module_info_description: 'Beschreibung',
      module_info_compatible_plugins: 'Kompatible Plugins',
      module_info_compatibility: 'Kompatibilität',
      module_info_default_value: 'Standardwert',
      no_description_available: 'Keine Beschreibung verfügbar',
      close: 'Schließen',
      rename_group: 'Gruppe umbenennen',
      disassemble_group: 'Gruppe auflösen',
      delete_group_content: 'Gruppe und Inhalt löschen',
      delete_group_content_title: 'Gruppe und Inhalt löschen',
      delete_group_content_message: 'Möchtest du "{name}" und alle darin enthaltenen Module wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
      select_sound: 'Sound auswählen',
      sounds: 'Sounds',
      sound: 'Sound',
      clear: 'Löschen',
      search_sounds: 'Sounds durchsuchen... (z.B. "block stone break")',
      no_sounds_found: 'Keine Sounds für "{search}" gefunden',
      configure_effects: 'Effekte konfigurieren',
      effects_selected: 'Effekte ausgewählt',
      effect_selected: 'Effekt ausgewählt',
      clear_all: 'Alle löschen',
      no_effects_found: 'Keine Effekte gefunden',
      added: 'Hinzugefügt',
      selected_effects: 'Ausgewählte Effekte',
      no_effects_selected: 'Keine Effekte ausgewählt',
      click_effect_to_add: 'Klicke links auf einen Effekt, um ihn hinzuzufügen',
      amplifier: 'Verstärkung (0 = Stufe I)',
      probability: 'Wahrscheinlichkeit (0.0 - 1.0)',
      ambient: 'Ambient (reduzierte Partikel)',
      cancel: 'Abbrechen',
      save_effects: 'Effekte speichern',
      shulker_hitboxes: 'Shulker-Hitboxen',
      barrier_hitboxes: 'Barrier-Hitboxen',
      shulker_format: 'Format: x,y,z Breite Höhe Ausrichtung',
      barrier_format: 'Format: [x,y,z]',
      shulker: 'Shulker',
      barrier: 'Barriere',
      offset: 'Versatz',
      active: 'Aktiv',
      inactive: 'Inaktiv',
      offset_xyz: 'Versatz (X, Y, Z)',
      size: 'Größe',
      width: 'Breite',
      height: 'Höhe',
      orientation: 'Ausrichtung',
      add: 'Hinzufügen',
      items: 'Items',
      click_item_to_pick: 'Klicke auf ein Item, um es aufzunehmen, dann klicke auf einen Slot, um es zu platzieren.',
      double_click_to_edit: 'Doppelklicke auf eine Zelle, um die Bearbeitung zu aktivieren, dann wähle hier Items aus.',
      search_items: 'Items durchsuchen...',
      clear_recipe: 'Rezept löschen',
      clear_recipe_tooltip: 'Alle Items aus dem Rezept entfernen',
      click_to_view_lore: 'Klicke, um die vollständige Lore anzuzeigen',
      no_lore: 'Keine Lore vorhanden',
      add_material: 'Material hinzufügen',
      drop_quantity: 'Menge',
      drop_probability: 'Wahrscheinlichkeit',
      drop_options: 'Optionen',
      export_methods: 'Exportmethoden',
      categories: 'Kategorien',
      change_category: 'Kategorie ändern',
      clear_category: 'Kategoriefilter löschen',
      no_export_for_module: 'Das aktuelle Projektformat "{format}" hat keinen Export für {module}.',
      click_to_setup_recipe: 'Klicke, um ein Rezept einzurichten',
      crafting_table_recipe: 'Rezepte',
      editing_crafting_recipe: 'Du bearbeitest das Handwerksrezept.',
      viewing_crafting_recipe: 'Ansicht des Handwerksrezepts. Doppelklicke auf eine Zelle, um die Bearbeitung zu aktivieren.',
      double_click_to_edit_cell: 'Doppelklicke zum Bearbeiten',
      empty_slot_double_click: 'Leerer Slot (Doppelklicke zum Bearbeiten)',
      right_click_to_remove: 'Rechtsklick zum Entfernen',
      click_to_select_item: 'Klicke, um ein Item auszuwählen',
      add_recipe: 'Rezept hinzufügen',
      no_recipes: 'Keine Rezepte konfiguriert',
      add_recipe_hint: 'Klicke, um ein Rezept für dieses Item hinzuzufügen',
      click_recipe_to_edit: 'Klicke auf ein Rezept, um es zu bearbeiten.',
      choose_recipe_type: 'Wähle den Rezepttyp, den du hinzufügen möchtest.',
      all_recipe_types_added: 'Alle Rezepttypen wurden hinzugefügt.',
      recipes: 'Rezepte',
      recipe_type_shaped: 'Geformt',
      recipe_type_shapeless: 'Formlos',
      recipe_type_furnace: 'Ofen',
      recipe_type_blasting: 'Hochofen',
      recipe_type_smoking: 'Räucherofen',
      recipe_type_campfire: 'Lagerfeuer',
      recipe_type_stonecutting: 'Steinsäge',
      recipe_type_brewing: 'Brauen',
      recipe_type_smithing: 'Schmieden',
      recipe_shaped_desc: 'Erfordert Zutaten in einer bestimmten Form',
      recipe_shapeless_desc: 'Erlaubt, dass jede Zutat in einen beliebigen Slot gelegt werden kann',
      recipe_furnace_desc: 'Rezept für den Ofen',
      recipe_blasting_desc: 'Rezept für den Hochofen',
      recipe_smoking_desc: 'Rezept für den Räucherofen',
      recipe_campfire_desc: 'Rezept für das Lagerfeuer',
      recipe_stonecutting_desc: 'Rezept für die Steinsäge',
      recipe_brewing_desc: 'Rezept für den Braustand',
      recipe_smithing_desc: 'Rezept für den Schmiedetisch (Nexo Addon)',
      cooking_time: 'Kochzeit (Ticks)',
      experience: 'Erfahrung',
      input_item: 'Eingabe-Item',
      ingredient: 'Zutat',
      remove_recipe: 'Rezept entfernen',
      recipe_configured: 'Rezept konfiguriert'
    },

    // ===== DEFAULT =====
    default: {
      next: 'Weiter',
      back: 'Zurück',
      finish: 'Fertigstellen'
    },

    // ===== CHANGELOG =====
    changelog: {
      new_features: 'Neue Funktionen',
      improvements: 'Verbesserungen',
      bug_fixes: 'Fehlerbehebungen',
      feature_blueprint_system: 'Blueprint-System (Erstelle Items mit Bausteinen!)',
      feature_gui_creator: 'GUI-Ersteller (GUIs per Drag & Drop?)',
      feature_bulk_edit: 'Massenbearbeitungsmodus (Schnelle Mehrfach-Item-Bearbeitung)',
      feature_environment_servers: 'Umgebungsserver-Instanzen (Eine Möglichkeit, Minecraft-Server-Versionen zu verwalten)',
      feature_denizen_download: 'Automatischer Denizen-Download (Denizen wird für GUI und Skripting verwendet!)',
      feature_echo_integration: 'Echo-Integration (Echo ist zurück!)',
      improvement_editor_experience: 'Verbesserte Editor-Erfahrung',
      improvement_style_refinements: 'Stil-Verfeinerungen in der gesamten App',
      improvement_overlay_close: 'Overlay-Fenster schließen jetzt bei Navigation',
      improvement_legacy_removed: 'Legacy-Bearbeitungsmodus entfernt',
      improvement_mcmeta_animations: 'Mcmeta-Animationen spielen jetzt auch in der 2D-Vorschau in Namespaces ab',
      fix_premium_projects: 'Premium-Benutzer haben keine begrenzten Projekte mehr',
      fix_json_texture_paths: 'JSON-Texturpfade verwenden jetzt korrekte Item-IDs',
      fix_glyphs_export: 'Glyphen werden korrekt für Nexo exportiert',
      fix_bbmodel_uv: 'BBModel-zu-JSON-UV-Zuordnung behoben',
      fix_multi_texture: 'Multi-Textur-BBModels laden korrekt',
      fix_premium_recognition: 'Premium-Erkennung bei der Projekterstellung',
      fix_author_field: 'Autorenfeld füllt sich automatisch im Erstellungsbildschirm',
      fix_plugins_transfer: 'Plugins werden beim Versionswechsel korrekt übertragen',
      fix_footer_version: 'Footer-Version wird sofort aktualisiert'
    },

    // ===== MODULES =====
    modules: {
      attackKnockback: { display: 'Angriffsrückstoß', description: 'Steuert, wie weit Ziele beim Treffer mit dem Item zurückgestoßen werden.' },
      attackSpeed: { display: 'Angriffsgeschwindigkeit', description: 'Steuert, wie schnell der Spieler angreifen kann, während er das Item hält.' },
      baseMaterial: { display: 'Basismaterial', description: 'Gibt das Material an, auf dem das Item basiert.' },
      'block-drops': { display: 'Block-Drops', description: 'Konfiguriere, welche Items fallen, wenn der Block abgebaut wird' },
      'block-explosion-resistance': { display: 'Explosionswiderstand', description: 'Legt fest, wie widerstandsfähig der Block gegen Explosionen ist' },
      'block-gravity': { display: 'Schwerkraft', description: 'Lässt den Block fallen, wenn er nicht gestützt wird (wie Sand/Kies)' },
      'block-hardness': { display: 'Blockhärte', description: 'Legt den Härtewert für den Block fest (wie lange es dauert, ihn abzubauen)' },
      'block-light-emission': { display: 'Lichtemission', description: 'Legt die Lichtstufe fest, die dieser Block emittiert (0-15)' },
      'block-mining-level': { display: 'Abbaustufe', description: 'Legt die minimale Werkzeugstufe fest, die zum Abbau dieses Blocks erforderlich ist' },
      'block-mining-tool': { display: 'Abbauwerkzeug', description: 'Gibt an, welches Werkzeug zum Abbau dieses Blocks erforderlich ist' },
      'block-placement-rules': { display: 'Platzierungsregeln', description: 'Konfiguriere, wo und wie dieser Block platziert werden kann' },
      'block-storage': { display: 'Lagercontainer', description: 'Konfiguriere den Block als Lagercontainer mit anpassbarem Inventar' },
      blockBreakSpeed: { display: 'Blockabbau-Geschwindigkeit', description: 'Steuert, wie schnell Blöcke abgebaut werden.' },
      blockInteractionRange: { display: 'Blockinteraktionsreichweite', description: 'Steuert, wie weit du mit Blöcken interagieren kannst.' },
      consumable: { display: 'Verbrauchbar', description: 'Ermöglicht es, dein Item zu verbrauchen (wie einen Trank).' },
      'consume-anim': { display: 'Verbrauchsanimation', description: 'Die Animation, die beim Verbrauchen des Items abgespielt wird.' },
      consume_effects: { display: 'Verbrauchseffekte', description: 'Effekte, die beim Verbrauchen dieses Items angewendet werden (Trank-Effekte, Teleport, Sounds).' },
      consume_particles: { display: 'Verbrauchspartikel', description: 'Ob Partikel beim Verbrauchen des Items angezeigt werden sollen.' },
      consume_seconds: { display: 'Verbrauchsdauer', description: 'Zeit in Sekunden, um das Item zu verbrauchen.' },
      consume_sound: { display: 'Verbrauchssound', description: 'Der Sound, der beim Verbrauchen des Items abgespielt wird.' },
      recipe: { display: 'Rezepte', description: 'Definiert Handwerksrezepte, um dieses Item herzustellen' },
      customModelData: { display: 'Benutzerdefinierte Modelldaten', description: 'Legt die benutzerdefinierten Modelldaten für Ressourcenpakete fest.' },
      damage: { display: 'Schaden', description: 'Steuert, wie viel Schaden ein Item beim Angriff verursacht.' },
      disableEnchanting: { display: 'Verzaubern deaktivieren', description: 'Deaktiviert die Fähigkeit, das Item zu verzaubern.' },
      displayTransform: { display: 'Anzeigetransformation', description: 'Definiert, welche Modellansicht zur Darstellung der Möbel verwendet wird' },
      durability: { display: 'Haltbarkeit', description: 'Legt die maximale Anzahl von Nutzungen fest, bevor das Item bricht.' },
      enchantable: { display: 'Verzauberbar', description: 'Legt die maximale Verzauberungskosten für dieses Item auf dem Verzauberungstisch fest' },
      enchantmentGlintOverride: { display: 'Verzauberungsglanz überschreiben', description: 'Legt einen Überschreibungsstatus für den Verzauberungsglanz fest.' },
      equippable: { display: 'Anlegbar', description: 'Ermöglicht das Anlegen des Items in den Rüstungsslots.' },
      'exclude-from-inventory': { display: 'Von Inventar ausschließen', description: 'Deaktiviert die Anzeige des Items in der Nexo-Plugin-GUI' },
      'food_can-always-eat': { display: 'Immer essbar', description: 'Ob der Spieler dieses Essen auch bei vollem Hunger essen kann.' },
      'furniture-block_light': { display: 'Blocklicht', description: 'Legt die Blocklichtstufe für Möbel fest' },
      'craftengine-ground-distance': { display: 'Bodenabstand', description: 'Höhenversatz der item_display-Entität über dem Boden (Y-Achse)' },
      'craftengine-rotation': { display: 'Rotation', description: 'Platzierungs-Rotationsrastung für diese Möbel' },
      'craftengine-furniture-hit-times': { display: 'Trefferanzahl', description: 'Anzahl der Treffer, die erforderlich sind, um diese Möbel zu zerbrechen' },
      'furniture-block_sounds-break_sound': { display: 'Zerbrech-Sound', description: 'Sound beim Zerbrechen der Möbel' },
      'furniture-block_sounds-fall_sound': { display: 'Fall-Sound', description: 'Sound beim Fallen auf die Möbel' },
      'furniture-block_sounds-hit_sound': { display: 'Treffer-Sound', description: 'Sound beim Treffen der Möbel' },
      'furniture-block_sounds-place_sound': { display: 'Platzier-Sound', description: 'Sound beim Platzieren der Möbel' },
      'furniture-block_sounds-step_sound': { display: 'Schritt-Sound', description: 'Sound beim Betreten der Möbel' },
      'furniture-display-transform': { display: 'Anzeigetransformation', description: 'Legt die Anzeigetransformation für Möbel fest' },
      'furniture-positioning': { display: 'Positionierung', description: 'Legt den Möbel-Entitätstyp fest (Vertikal = armor_stand, Oberfläche = item_frame)' },
      'furniture-sit_height': { display: 'Sitzhöhe', description: 'Legt die Höhe fest, auf der Spieler auf dieser Möbel sitzen' },
      'furniture-drop-silktouch': { display: 'Seidige Berührung', description: 'Möbel nur mit Seidiger Berührung erhalten' },
      'furniture-hitbox-barrier': { display: 'Barriere-Hitbox', description: 'Konfiguriere die Möbel-Barriere-Hitbox als Koordinatengröße' },
      'furniture-hitbox-interactions': { display: 'Hitbox-Interaktionen', description: 'Konfiguriere die Möbel-Hitbox-Interaktionen' },
      'furniture-hitbox-shulkers': { display: 'Shulker-Hitbox', description: 'Konfiguriere die Möbel-Hitbox für Shulker' },
      'furniture-limited_placing-floor': { display: 'Bodenplatzierung erlauben', description: 'Erlaube Platzierung auf dem Boden' },
      'furniture-limited_placing-roof': { display: 'Deckenplatzierung erlauben', description: 'Erlaube Platzierung von Möbeln an der Decke' },
      'furniture-limited_placing-type': { display: 'Eingeschränkter Platzierungstyp', description: 'Typ der eingeschränkten Platzierung für Möbel' },
      'furniture-limited_placing-wall': { display: 'Wandplatzierung erlauben', description: 'Erlaube Platzierung an der Wand' },
      'furniture-loot': { display: 'Möbel-Beute', description: 'Konfiguriere Beute-Drops für Möbel' },
      'furniture-restricted_rotation': { display: 'Eingeschränkte Rotation', description: 'Schränke die Möbel-Rotation ein' },
      'furniture-rotatable': { display: 'Rotierbar', description: 'Mache Möbel rotierbar' },
      'furniture-sky_light': { display: 'Himmelslicht', description: 'Legt die Himmelslichtstufe für Möbel fest' },
      'furniture-tracking-rotation': { display: 'Rotationsverfolgung', description: 'Aktiviere die Rotationsverfolgung für Möbel' },
      gravity: { display: 'Schwerkraft', description: 'Steuert, ob das Item beim Fallenlassen von der Schwerkraft beeinflusst wird.' },
      hideTooltip: { display: 'Tooltip ausblenden', description: 'Blendet den gesamten Tooltip beim Überfahren des Items aus' },
      jumpStrength: { display: 'Sprungkraft', description: 'Steuert die Sprungkraft-Verstärkung.' },
      knockbackResistance: { display: 'Rückstoßwiderstand', description: 'Steuert den Widerstand gegen Rückstoß.' },
      luck: { display: 'Glück', description: 'Steuert die Glücksstufe.' },
      'max-health': { display: 'Maximale Gesundheit', description: 'Steuert die maximale Gesundheit.' },
      maxAbsorption: { display: 'Maximale Absorption', description: 'Steuert den maximalen Absorptionsbetrag.' },
      maxStackSize: { display: 'Maximale Stapelgröße', description: 'Definiert die maximale Anzahl von Items, die gestapelt werden können.' },
      'minimal-type': { display: 'Minimaler Typ', description: 'Legt den minimalen Werkzeugtyp fest, der erforderlich ist, um Drops von diesem Block zu erhalten' },
      miningEfficiency: { display: 'Abbaueffizienz', description: 'Steuert die Abbaugeschwindigkeits-Verstärkung.' },
      movementEfficiency: { display: 'Bewegungseffizienz', description: 'Steuert die Bewegungsgeschwindigkeits-Verstärkung.' },
      nutrition: { display: 'Nährwert', description: 'Legt den Nährwert für Nahrungsmittel fest.' },
      repairable: { display: 'Reparierbare Materialien', description: 'Welche Items in Ambossen zur Reparatur der Haltbarkeit verwendet werden sollen' },
      saturation: { display: 'Sättigung', description: 'Legt den Sättigungswert für Nahrungsmittel fest.' },
      'stringblock-block_sounds-break_sound': { display: 'Zerbrech-Sound', description: 'Sound, der abgespielt wird, wenn der Block zerbrochen wird' },
      'stringblock-block_sounds-place_sound': { display: 'Platzier-Sound', description: 'Sound, der abgespielt wird, wenn der Block platziert wird' },
      'stringblock-block_sounds-step_sound': { display: 'Schritt-Sound', description: 'Sound, der abgespielt wird, wenn auf dem Block gelaufen wird' },
      thrownDamage: { display: 'Wurf-Schaden', description: 'Schaden, der verursacht wird, wenn ein geworfener Dreizack (Dreizack-Verhalten) als Projektil trifft. Getrennt vom Nahkampf-Schaden.' },
      toolMaterial: { display: 'Werkzeugtyp', description: 'Wähle den Werkzeugtyp und die Materialstufe für dieses Werkzeug.' },
      unbreakable: { display: 'Unzerstörbar', description: 'Verhindert jeglichen Haltbarkeitsverlust und hält das Item intakt.' },
      useCooldown: { display: 'Nutzungs-Abklingzeit', description: 'Wendet eine Abklingzeit auf alle passenden Items bei Verwendung an' },
      weaponBehavior: { display: 'Waffen-Verhalten', description: 'Wie die Waffe verwendet wird: ein Nahkampf-Schwung, ein Vanilla-Speer (Stoß/Ladung, MC 1.21.11+), ein werfbarer Dreizack oder ein Bogen/Crossbow. Das richtige Basis-Item und die Mechaniken werden beim Export automatisch eingerichtet.' }
    }
  });

  // ===== SETTINGS TAB REGISTRIEREN =====
  try {
    nm.postAppSettingsTab({
      id: "german-language-pack-settings",
      expansionId: "german-language-pack",
      title: "🇩🇪 Deutsch",
      description: "Deutsches Sprachpaket – Einstellungen",
      order: 50,
      elements: [
        {
          id: "info",
          label: "💡 Info",
          type: "text",
          description: "Das Sprachpaket wurde geladen.\nGehe zu Einstellungen → Sprache → Deutsch",
          default: "",
          readonly: true
        },
        {
          id: "separator",
          type: "separator"
        },
        {
          id: "reload_btn",
          label: "🔄 Sprache neu laden",
          type: "button",
          description: "Lädt die deutsche Übersetzung neu",
          action: () => {
            api.console.log('🇩🇪 German language pack reloaded!');
          }
        }
      ]
    });
    api.console.log('✅ Settings tab registered');
  } catch (e) {
    api.console.error('❌ Settings tab error:', e.message);
  }

  api.console.log('✅ German language pack loaded!');
  api.console.log('🇩🇪 Go to Settings → Language → Deutsch');
};

module.exports.metadata = {
  id: "german-language-pack",
  version: "1.0.0",
  author: "McAffe13",
  description: "Deutsches Sprachpaket für Nexo Maker",
  apiKey: "nmk_Vpb0maBfN5HYcPFjawujlD8_bdcvnIUhr0neFc7gweY"
};